# Generated by Django 3.2.4 on 2023-01-23 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_borrowed', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amount_repayed', models.DecimalField(decimal_places=2, max_digits=8)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_borrowed', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amount_repayed', models.DecimalField(decimal_places=2, max_digits=8)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('borrowers', models.ManyToManyField(related_name='expenses_borrowed', to='expenses.Borrower')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses_lent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
