# Generated by Django 3.2.4 on 2023-01-27 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_borrowed', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amount_repayed', models.DecimalField(decimal_places=2, max_digits=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True, max_length=300, null=True)),
                ('totalexpense', models.DecimalField(decimal_places=2, max_digits=8)),
                ('lenders_share', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('totalborrowed', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('totalrepayed', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_settled', models.BooleanField(default=False)),
                ('borrowers', models.ManyToManyField(related_name='expenses_borrowed', to='expenses.Borrower')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses_lent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
