# Generated by Django 3.2.4 on 2023-01-24 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expense',
            name='borrowers',
            field=models.ManyToManyField(blank=True, null=True, related_name='expenses_borrowed', to='expenses.Borrower'),
        ),
    ]
