# Generated by Django 3.2.6 on 2023-05-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseparticipant',
            name='name',
            field=models.CharField(default='<django.db.models.fields.UUIDField>', max_length=100),
        ),
    ]
