# Generated by Django 3.2.6 on 2023-06-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_alter_expense_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payed_back',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='expense',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
    ]
