# Generated by Django 3.2.6 on 2023-06-06 15:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expense', '0006_alter_expenseparticipant_expense'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expenseparticipant',
            unique_together={('account', 'expense')},
        ),
    ]
